### ISSUE TITLE
Running "Case-study-COVID-19-in-Singapore" demo using G3

### ISSUE THREAD

**Issue by farhour** [Xtra-Computing/G3#6]
Hi, I reviewed the "Case-study-COVID-19-in-Singapore" demo and executed it successfully on my system. However, I did not understand the relation between this demo and the G3 program. Here are my questions:

**1-** The "Case-study-COVID-19-in-Singapore" demo uses PyTorch LSTM and Linear modules to train the described 3-layered GNN module. So, to use G3 for the training, how do we change this defined PyThorh module to a G3 one?

**2-** How do we change the input data of this demo to one suitable for G3? As far as I realized, the datasets in the web-app demo are somehow different from the datasets in this demo.

**3-** In sum, implementing this demo with G3 is unclear. Therefore, I would appreciate that if you clarify this. 

Thanks.

**Comment by lushl9301** [comment]
Hi Farhour,

Thanks for reviewing the case study. Glad that it works well on your system.

To clarify your concern: the demo code we included in this repo is more like a sanity check for G3's implementation of this demo. We found other python-based training system like DGL and PyG more friendly to be used for demonstration the COVID case study. It would be good to opensource it for people to review our effort on fighting covid-19.

However, the code base of covid-19 demo on G3 is hard-coded; the LSTM part is not 100% functional. Therefore it is not yet pushed to this repo yet. sorry about the confusion made.

**Comment by farhour** [comment]
Thanks, lushl9301 for your helpful and quick reply.

Yes, my main concern was the implementation of LSTM with the current G3 functionality. You made it clear.

I hope to see future updates and more detailed samples of G3. **Good job! Keep it up!**
