### ISSUE TITLE
Using Time Series data to Train a GNN in G3

### ISSUE THREAD

**Issue by farhour** [Xtra-Computing/G3#7]
Hi,

I opened issue #6 and asked about the Running "Case-study-COVID-19-in-Singapore" demo using G3. You stated that the code base of the Covid-19 demo on G3 is hard-coded, and the LSTM part is not 100% functional. Therefore it is not pushed to this repo yet.

However, I have another question related to this. I have a dataset containing some time-series data on a GNN. I want to train a GNN using the G3 for the prediction over this time-series.

For example, you can consider a dataset of Covid-19 cases. So, based on this, I want to train 10 sequential days of confirmed cases in 5 cities to predict the 11th day of confirmed cases in these cities. So my question is that, is it possible to use time-series data to train a GNN in current the current G3?

I reviewed the sample data you put in this repo for the G3 (G3/dataset/gcn/). None of them are time-series data and time-series prediction. Regarding the current API of G3 and the lack of the LSTM module in it, I want to know whether we can train a model for time series prediction using G3 or not.

Thanks for your time. :)

**Comment by lushl9301** [comment]
Hi thanks for your interests.

The usage of GNN training system for time-series data is still under investigation. We see several recent works that are focusing on time-series data. would you please check the related publications? The correct way of integrating LSTM to GNN is not known. G3 currently does not support time series prediction.

related work that may be interesting
Yu, Bing, Haoteng Yin, and Zhanxing Zhu. "Spatio-temporal graph convolutional networks: a deep learning framework for traffic forecasting." Proceedings of the 27th International Joint Conference on Artificial Intelligence. 2018.

**Comment by farhour** [comment]
Thank you @lushl9301 for this great explanation.
